// components/prompt-kit/markdown.tsx
import { cn } from "@/lib/utils"
import { marked } from "marked"
import { memo, useId, useMemo } from "react"
import ReactMarkdown, { Components } from "react-markdown"
import remarkGfm from "remark-gfm"
import { CodeBlock, CodeBlockCode } from "./code-block"

export type MarkdownProps = {
  children: string
  id?: string
  className?: string
  components?: Partial<Components>
}

function parseMarkdownIntoBlocks(markdown: string): string[] {
  const tokens = marked.lexer(markdown)
  return tokens.map((token) => token.raw)
}

function extractLanguage(className?: string): string {
  if (!className) return "plaintext"
  const match = className.match(/language-(\w+)/)
  return match ? match[1] : "plaintext"
}

const INITIAL_COMPONENTS: Partial<Components> = {
  code: function CodeComponent({ className, children, ...props }) {
    const isInline =
      !props.node?.position?.start.line ||
      props.node?.position?.start.line === props.node?.position?.end.line

    if (isInline) {
      return (
        <span
          className={cn(
            "bg-primary-foreground rounded-sm px-1 font-mono text-sm",
            className
          )}
          {...props}
        >
          {children}
        </span>
      )
    }

    const language = extractLanguage(className)

    return (
      <CodeBlock className={className}>
        <CodeBlockCode code={children as string} language={language} />
      </CodeBlock>
    )
  },
  pre: function PreComponent({ children }) {
    return <>{children}</>
  },
}

const MemoizedMarkdownBlock = memo(
  function MarkdownBlock({
    content,
    components = INITIAL_COMPONENTS,
    className,
  }: {
    content: string
    components?: Partial<Components>
    className?: string
  }) {
    return (
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={components}
        className={className}
      >
        {content}
      </ReactMarkdown>
    )
  },
  function propsAreEqual(prevProps, nextProps) {
    return prevProps.content === nextProps.content
  }
)

MemoizedMarkdownBlock.displayName = "MemoizedMarkdownBlock"

function MarkdownComponent({
  children,
  id,
  className,
  components = INITIAL_COMPONENTS,
}: MarkdownProps) {
  const generatedId = useId()
  const blockId = id ?? generatedId
  const blocks = useMemo(() => parseMarkdownIntoBlocks(children), [children])

  return (
    <>
      {blocks.map((block, index) => (
        <MemoizedMarkdownBlock
          key={`${blockId}-block-${index}`}
          content={block}
          components={components}
          className={className}
        />
      ))}
    </>
  )
}

const Markdown = memo(MarkdownComponent)
Markdown.displayName = "Markdown"

export { Markdown }

// components/prompt-kit/markdown/Markdown.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { ref, computed, watchEffect } from 'vue'
import { marked } from 'marked'
import { cn } from '@/lib/utils'
import { CodeBlock, CodeBlockCode } from '../code-block'

interface Props {
  children?: string
  id?: string
  class?: HTMLAttributes['class']
}

const props = defineProps<Props>()

const blockId = ref(props.id || Math.random().toString(36).substr(2, 9))

const parseMarkdownIntoBlocks = (markdown: string): string[] => {
  const tokens = marked.lexer(markdown)
  return tokens.map((token) => token.raw)
}

const blocks = computed(() => {
  if (!props.children) return []
  return parseMarkdownIntoBlocks(props.children)
})

const extractLanguage = (className?: string): string => {
  if (!className) return 'plaintext'
  const match = className.match(/language-(\w+)/)
  return match ? match[1] : 'plaintext'
}

const isInlineCode = (node: any): boolean => {
  return !node?.position?.start.line ||
    node?.position?.start.line === node?.position?.end.line
}

const processMarkdown = (content: string): string => {
  // This is a simplified version - you might want to use a proper Vue markdown renderer
  // like @nuxtjs/mdc or similar for production
  return marked(content, {
    breaks: true,
    gfm: true,
  })
}
</script>

<template>
  <div :class="props.class">
    <div 
      v-for="(block, index) in blocks" 
      :key="`${blockId}-block-${index}`"
      v-html="processMarkdown(block)"
    />
  </div>
</template>
